[package]
name = "stack-assembly-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
beau_collector = "0.2.1"
mockall = "0.13.1"
once_cell = "1.21.1"
regex = "1.11.1"
