
all:
	@refal/refc task1.ref && echo "------------------------------" && refal/refgo task1.rsl

2:
	@refal/refc task2.ref && echo "------------------------------" && refal/refgo task2.rsl

clean:
	@rm task1.rsl
	@rm task2.rsl


.PHONY: all
